name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo install wasm-pack
    - run: wasm-pack build --release --target web --out-name wasm --out-dir ./public
<<<<<<< HEAD
    - run: cp ./index.html ./public/index.html
=======
>>>>>>> cdbc5e3980dc0bc0004495671b7d9f4b78d8bfb5
    - run: rm -rf ./public/.gitignore

    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
